import os
import json




# Estado global de la aplicación
# False = modo claro, True = modo oscuro



# Estado global
MODO_OSCURO = False

# Colores (modo claro por ahora)
COLOR_FONDO_PRESENTACION = "#FFFFFF"

# Colores modo claro
COLOR_FONDO_VENTANA_CLARO = "#FFFFFF"
COLOR_TARJETAS_CLARO = "#EBEBEB"

# Colores modo oscuro (los que me mandaste)
COLOR_FONDO_VENTANA_OSCURO = "#171717"
COLOR_TARJETAS_OSCURO = "#0F0F0F"

# Colores activos (se actualizan con actualizar_tema)
COLOR_FONDO_VENTANA = COLOR_FONDO_VENTANA_CLARO
COLOR_TARJETAS = COLOR_TARJETAS_CLARO



# Switch (colores modo claro)
COLOR_SWITCH_RIEL_APAGADO_CLARO = "#335FB0"   # gris    
COLOR_SWITCH_RIEL_ENCENDIDO_CLARO = "#0D0D0D" # blanco  
COLOR_SWITCH_BOTON_CLARO = "#02215C"       
COLOR_SWITCH_BOTON_HOVER_CLARO = "#00338C"                  

# Switch (colores modo oscuro)
COLOR_SWITCH_RIEL_APAGADO_OSCURO = "#9CA3AF"   # gris oscuro
COLOR_SWITCH_RIEL_ENCENDIDO_OSCURO = "#7D7D7D" # igual que tarjeta oscura
COLOR_SWITCH_BOTON_OSCURO = "#4A4A4A"
COLOR_SWITCH_BOTON_HOVER_OSCURO = "#3B3B3B"

# Switch (colores activos)
COLOR_SWITCH_RIEL_APAGADO = COLOR_SWITCH_RIEL_APAGADO_CLARO
COLOR_SWITCH_RIEL_ENCENDIDO = COLOR_SWITCH_RIEL_ENCENDIDO_CLARO
COLOR_SWITCH_BOTON = COLOR_SWITCH_BOTON_CLARO
COLOR_SWITCH_BOTON_HOVER = COLOR_SWITCH_BOTON_HOVER_CLARO



# Color del texto para la etiqueta "URL:" (por modo)
# Se pide que sea igual al color del fondo de la ventana principal
COLOR_TEXTO_URL_CLARO = "#02215C"
COLOR_TEXTO_URL_OSCURO = COLOR_TARJETAS_CLARO

# Color activo del texto "URL:" (se actualiza en actualizar_tema)
COLOR_TEXTO_URL = COLOR_TEXTO_URL_CLARO





# ---------------------------
# Barra de progreso - Colores por modo
# ---------------------------

# Color del riel (fondo) de la barra
COLOR_BARRA_PROGRESO_FONDO_CLARO = "#FFFFFF"
COLOR_BARRA_PROGRESO_FONDO_OSCURO = "#171717"

# Color del relleno (progreso) de la barra
# Puedes cambiarlo después si quieres otro tono de azul
COLOR_BARRA_PROGRESO_RELLENO_CLARO = "#02215C"
COLOR_BARRA_PROGRESO_RELLENO_OSCURO = COLOR_TARJETAS_CLARO

# Colores activos (se actualizan con actualizar_tema)
COLOR_BARRA_PROGRESO_FONDO = COLOR_BARRA_PROGRESO_FONDO_CLARO
COLOR_BARRA_PROGRESO_RELLENO = COLOR_BARRA_PROGRESO_RELLENO_CLARO



# ---------------------------
# Textbox (URL) - Colores por modo
# ---------------------------

# NOTA:
# Se dejan en None para que, por ahora, el CTkEntry conserve su apariencia actual.
# Cuando quieras cambiar colores, aquí pones los hex (por ejemplo "#FFFFFF", etc.)

COLOR_TEXBOX_URL_FONDO_CLARO = "#FFFFFF"
COLOR_TEXBOX_URL_TEXTO_CLARO = "#02215C"
COLOR_TEXBOX_URL_PLACEHOLDER_CLARO = "#02215C"
COLOR_TEXBOX_URL_BORDE_CLARO = "#FFFFFF"

COLOR_TEXBOX_URL_FONDO_OSCURO = "#171717"
COLOR_TEXBOX_URL_TEXTO_OSCURO = "#EBEBEB"
COLOR_TEXBOX_URL_PLACEHOLDER_OSCURO = "#EBEBEB"
COLOR_TEXBOX_URL_BORDE_OSCURO = "#171717"

# Colores activos (se actualizan con actualizar_tema)
COLOR_TEXBOX_URL_FONDO = COLOR_TEXBOX_URL_FONDO_CLARO
COLOR_TEXBOX_URL_TEXTO = COLOR_TEXBOX_URL_TEXTO_CLARO
COLOR_TEXBOX_URL_PLACEHOLDER = COLOR_TEXBOX_URL_PLACEHOLDER_CLARO
COLOR_TEXBOX_URL_BORDE = COLOR_TEXBOX_URL_BORDE_CLARO



# ---------------------------
# Botón "x" (borrar por renglón) - Colores por modo
# ---------------------------

# Color del texto de la "x"
COLOR_BOTON_X_TEXTO_CLARO = "#02215C"
COLOR_BOTON_X_TEXTO_OSCURO = "#EBEBEB"

# Color activo (se actualiza con actualizar_tema)
COLOR_BOTON_X_TEXTO = COLOR_BOTON_X_TEXTO_CLARO





# ---------------------------
# Tarjeta "Formato" - Colores por modo
# ---------------------------


COLOR_SELECT_FORMATO_DROPDOWN_HOVER_CLARO = "#013494"
COLOR_SELECT_FORMATO_DROPDOWN_HOVER_OSCURO = "#434447"  # None = no forzamos, se queda como está
COLOR_SELECT_FORMATO_DROPDOWN_HOVER = COLOR_SELECT_FORMATO_DROPDOWN_HOVER_CLARO

# Select box (ComboBox)
COLOR_SELECT_FORMATO_FONDO_CLARO = "#022C7A"   #
COLOR_SELECT_FORMATO_TEXTO_CLARO = "#FFFFFF"
COLOR_SELECT_FORMATO_BORDE_CLARO = "#013494"   #
COLOR_SELECT_FORMATO_BOTON_CLARO = "#02215C"      #azul fuerte       #02215C
COLOR_SELECT_FORMATO_BOTON_HOVER_CLARO = "#013494"    #Azul claro    #022C7A
COLOR_SELECT_FORMATO_DROPDOWN_FONDO_CLARO = "#022C7A"  #
COLOR_SELECT_FORMATO_DROPDOWN_TEXTO_CLARO = "#FFFFFF"

COLOR_SELECT_FORMATO_FONDO_OSCURO = "#343638"   #
COLOR_SELECT_FORMATO_TEXTO_OSCURO = "#FFFFFF"
COLOR_SELECT_FORMATO_BORDE_OSCURO = "#343638"   #
COLOR_SELECT_FORMATO_BOTON_OSCURO = "#2B2B2B"        #azul fuerte
COLOR_SELECT_FORMATO_BOTON_HOVER_OSCURO = "#3A3A3A"
COLOR_SELECT_FORMATO_DROPDOWN_FONDO_OSCURO = "#343638"   #
COLOR_SELECT_FORMATO_DROPDOWN_TEXTO_OSCURO = "#FFFFFF"

# Select box (activos)
COLOR_SELECT_FORMATO_FONDO = COLOR_SELECT_FORMATO_FONDO_CLARO
COLOR_SELECT_FORMATO_TEXTO = COLOR_SELECT_FORMATO_TEXTO_CLARO
COLOR_SELECT_FORMATO_BORDE = COLOR_SELECT_FORMATO_BORDE_CLARO
COLOR_SELECT_FORMATO_BOTON = COLOR_SELECT_FORMATO_BOTON_CLARO
COLOR_SELECT_FORMATO_BOTON_HOVER = COLOR_SELECT_FORMATO_BOTON_HOVER_CLARO
COLOR_SELECT_FORMATO_DROPDOWN_FONDO = COLOR_SELECT_FORMATO_DROPDOWN_FONDO_CLARO
COLOR_SELECT_FORMATO_DROPDOWN_TEXTO = COLOR_SELECT_FORMATO_DROPDOWN_TEXTO_CLARO


# Textbox (Formato) - por ahora igual que el textbox de URL (mismos colores actuales)
COLOR_TEXBOX_FORMATO_FONDO_CLARO = COLOR_TEXBOX_URL_FONDO_CLARO
COLOR_TEXBOX_FORMATO_TEXTO_CLARO = COLOR_TEXBOX_URL_TEXTO_CLARO
COLOR_TEXBOX_FORMATO_PLACEHOLDER_CLARO = COLOR_TEXBOX_URL_PLACEHOLDER_CLARO
COLOR_TEXBOX_FORMATO_BORDE_CLARO = COLOR_TEXBOX_URL_BORDE_CLARO

COLOR_TEXBOX_FORMATO_FONDO_OSCURO = COLOR_TEXBOX_URL_FONDO_OSCURO
COLOR_TEXBOX_FORMATO_TEXTO_OSCURO = COLOR_TEXBOX_URL_TEXTO_OSCURO
COLOR_TEXBOX_FORMATO_PLACEHOLDER_OSCURO = COLOR_TEXBOX_URL_PLACEHOLDER_OSCURO
COLOR_TEXBOX_FORMATO_BORDE_OSCURO = COLOR_TEXBOX_URL_BORDE_OSCURO

# Textbox (Formato) activos
COLOR_TEXBOX_FORMATO_FONDO = COLOR_TEXBOX_FORMATO_FONDO_CLARO
COLOR_TEXBOX_FORMATO_TEXTO = COLOR_TEXBOX_FORMATO_TEXTO_CLARO
COLOR_TEXBOX_FORMATO_PLACEHOLDER = COLOR_TEXBOX_FORMATO_PLACEHOLDER_CLARO
COLOR_TEXBOX_FORMATO_BORDE = COLOR_TEXBOX_FORMATO_BORDE_CLARO


# Botón "Examinar"
COLOR_BOTON_EXAMINAR_FONDO_CLARO = "#02215C"
COLOR_BOTON_EXAMINAR_HOVER_CLARO = "#022C7A"
COLOR_BOTON_EXAMINAR_TEXTO_CLARO = "#FFFFFF"

COLOR_BOTON_EXAMINAR_FONDO_OSCURO = COLOR_TARJETAS_CLARO
COLOR_BOTON_EXAMINAR_HOVER_OSCURO = "#FFFFFF"
COLOR_BOTON_EXAMINAR_TEXTO_OSCURO = "#171717"

# Botón "Examinar" activos
COLOR_BOTON_EXAMINAR_FONDO = COLOR_BOTON_EXAMINAR_FONDO_CLARO
COLOR_BOTON_EXAMINAR_HOVER = COLOR_BOTON_EXAMINAR_HOVER_CLARO
COLOR_BOTON_EXAMINAR_TEXTO = COLOR_BOTON_EXAMINAR_TEXTO_CLARO





# ---------------------------
# Persistencia de configuración
# ---------------------------

# Carpeta y archivo donde se guardará la configuración del usuario
CARPETA_DATOS = os.path.join(os.path.dirname(__file__), "datos")
RUTA_CONFIGURACION = os.path.join(CARPETA_DATOS, "configuracion.json")

def _asegurar_archivo_configuracion():
    """
    Crea la carpeta 'datos' y el archivo 'configuracion.json' si no existen.
    La primera vez deja el modo oscuro en False (modo claro).
    """
    if not os.path.exists(CARPETA_DATOS):
        os.makedirs(CARPETA_DATOS, exist_ok=True)

    if not os.path.exists(RUTA_CONFIGURACION):
        datos_iniciales = {"modo_oscuro": False}
        with open(RUTA_CONFIGURACION, "w", encoding="utf-8") as archivo:
            json.dump(datos_iniciales, archivo, ensure_ascii=False, indent=4)

def cargar_modo_desde_json():
    """
    Lee el modo (claro/oscuro) desde el JSON y actualiza la variable global MODO_OSCURO.
    Si hay error o el archivo está corrupto, se regresa a modo claro por seguridad.
    """
    global MODO_OSCURO

    _asegurar_archivo_configuracion()

    try:
        with open(RUTA_CONFIGURACION, "r", encoding="utf-8") as archivo:
            datos = json.load(archivo)

        # Si no existe la clave, se asume modo claro
        MODO_OSCURO = bool(datos.get("modo_oscuro", False))

    except Exception:
        # Si algo falla (archivo corrupto, etc.), volvemos a modo claro
        MODO_OSCURO = False

def guardar_modo_en_json():
    """
    Guarda el estado actual de MODO_OSCURO en el JSON.
    """
    _asegurar_archivo_configuracion()

    datos = {"modo_oscuro": bool(MODO_OSCURO)}
    with open(RUTA_CONFIGURACION, "w", encoding="utf-8") as archivo:
        json.dump(datos, archivo, ensure_ascii=False, indent=4)

def actualizar_tema():
    global COLOR_FONDO_VENTANA, COLOR_TARJETAS
    global COLOR_SWITCH_RIEL_APAGADO, COLOR_SWITCH_RIEL_ENCENDIDO, COLOR_SWITCH_BOTON, COLOR_SWITCH_BOTON_HOVER
    global COLOR_TEXTO_URL
    global COLOR_TEXBOX_URL_FONDO, COLOR_TEXBOX_URL_TEXTO, COLOR_TEXBOX_URL_PLACEHOLDER, COLOR_TEXBOX_URL_BORDE
    global COLOR_BARRA_PROGRESO_FONDO, COLOR_BARRA_PROGRESO_RELLENO
    global COLOR_BOTON_X_TEXTO

    global COLOR_SELECT_FORMATO_FONDO, COLOR_SELECT_FORMATO_TEXTO, COLOR_SELECT_FORMATO_BORDE
    global COLOR_SELECT_FORMATO_BOTON, COLOR_SELECT_FORMATO_BOTON_HOVER
    global COLOR_SELECT_FORMATO_DROPDOWN_FONDO, COLOR_SELECT_FORMATO_DROPDOWN_TEXTO


    global COLOR_SELECT_FORMATO_DROPDOWN_HOVER

    global COLOR_TEXBOX_FORMATO_FONDO, COLOR_TEXBOX_FORMATO_TEXTO, COLOR_TEXBOX_FORMATO_PLACEHOLDER, COLOR_TEXBOX_FORMATO_BORDE

    global COLOR_BOTON_EXAMINAR_FONDO, COLOR_BOTON_EXAMINAR_HOVER, COLOR_BOTON_EXAMINAR_TEXTO




    if MODO_OSCURO:
        COLOR_FONDO_VENTANA = COLOR_FONDO_VENTANA_OSCURO
        COLOR_TARJETAS = COLOR_TARJETAS_OSCURO

        COLOR_SWITCH_RIEL_APAGADO = COLOR_SWITCH_RIEL_APAGADO_OSCURO
        COLOR_SWITCH_RIEL_ENCENDIDO = COLOR_SWITCH_RIEL_ENCENDIDO_OSCURO
        COLOR_SWITCH_BOTON = COLOR_SWITCH_BOTON_OSCURO
        COLOR_SWITCH_BOTON_HOVER = COLOR_SWITCH_BOTON_HOVER_OSCURO


        COLOR_TEXBOX_URL_FONDO = COLOR_TEXBOX_URL_FONDO_OSCURO
        COLOR_TEXBOX_URL_TEXTO = COLOR_TEXBOX_URL_TEXTO_OSCURO
        COLOR_TEXBOX_URL_PLACEHOLDER = COLOR_TEXBOX_URL_PLACEHOLDER_OSCURO
        COLOR_TEXBOX_URL_BORDE = COLOR_TEXBOX_URL_BORDE_OSCURO



        # Select Formato
        COLOR_SELECT_FORMATO_FONDO = COLOR_SELECT_FORMATO_FONDO_OSCURO
        COLOR_SELECT_FORMATO_TEXTO = COLOR_SELECT_FORMATO_TEXTO_OSCURO
        COLOR_SELECT_FORMATO_BORDE = COLOR_SELECT_FORMATO_BORDE_OSCURO
        COLOR_SELECT_FORMATO_BOTON = COLOR_SELECT_FORMATO_BOTON_OSCURO
        COLOR_SELECT_FORMATO_BOTON_HOVER = COLOR_SELECT_FORMATO_BOTON_HOVER_OSCURO
        COLOR_SELECT_FORMATO_DROPDOWN_FONDO = COLOR_SELECT_FORMATO_DROPDOWN_FONDO_OSCURO
        COLOR_SELECT_FORMATO_DROPDOWN_TEXTO = COLOR_SELECT_FORMATO_DROPDOWN_TEXTO_OSCURO
        COLOR_SELECT_FORMATO_DROPDOWN_HOVER = COLOR_SELECT_FORMATO_DROPDOWN_HOVER_OSCURO

        # Textbox Formato
        COLOR_TEXBOX_FORMATO_FONDO = COLOR_TEXBOX_FORMATO_FONDO_OSCURO
        COLOR_TEXBOX_FORMATO_TEXTO = COLOR_TEXBOX_FORMATO_TEXTO_OSCURO
        COLOR_TEXBOX_FORMATO_PLACEHOLDER = COLOR_TEXBOX_FORMATO_PLACEHOLDER_OSCURO
        COLOR_TEXBOX_FORMATO_BORDE = COLOR_TEXBOX_FORMATO_BORDE_OSCURO

        # Botón Examinar
        COLOR_BOTON_EXAMINAR_FONDO = COLOR_BOTON_EXAMINAR_FONDO_OSCURO
        COLOR_BOTON_EXAMINAR_HOVER = COLOR_BOTON_EXAMINAR_HOVER_OSCURO
        COLOR_BOTON_EXAMINAR_TEXTO = COLOR_BOTON_EXAMINAR_TEXTO_OSCURO



        # Botón "x" por renglón
        COLOR_BOTON_X_TEXTO = COLOR_BOTON_X_TEXTO_OSCURO

        #barra progreso
        COLOR_BARRA_PROGRESO_FONDO = COLOR_BARRA_PROGRESO_FONDO_OSCURO
        COLOR_BARRA_PROGRESO_RELLENO = COLOR_BARRA_PROGRESO_RELLENO_OSCURO

        # Texto "URL:" igual al fondo de la ventana principal (modo oscuro)
        COLOR_TEXTO_URL = COLOR_TEXTO_URL_OSCURO
    else:
        COLOR_FONDO_VENTANA = COLOR_FONDO_VENTANA_CLARO
        COLOR_TARJETAS = COLOR_TARJETAS_CLARO

        COLOR_SWITCH_RIEL_APAGADO = COLOR_SWITCH_RIEL_APAGADO_CLARO
        COLOR_SWITCH_RIEL_ENCENDIDO = COLOR_SWITCH_RIEL_ENCENDIDO_CLARO
        COLOR_SWITCH_BOTON = COLOR_SWITCH_BOTON_CLARO
        COLOR_SWITCH_BOTON_HOVER = COLOR_SWITCH_BOTON_HOVER_CLARO

        COLOR_TEXBOX_URL_FONDO = COLOR_TEXBOX_URL_FONDO_CLARO
        COLOR_TEXBOX_URL_TEXTO = COLOR_TEXBOX_URL_TEXTO_CLARO
        COLOR_TEXBOX_URL_PLACEHOLDER = COLOR_TEXBOX_URL_PLACEHOLDER_CLARO
        COLOR_TEXBOX_URL_BORDE = COLOR_TEXBOX_URL_BORDE_CLARO




        # Select Formato
        COLOR_SELECT_FORMATO_FONDO = COLOR_SELECT_FORMATO_FONDO_CLARO
        COLOR_SELECT_FORMATO_TEXTO = COLOR_SELECT_FORMATO_TEXTO_CLARO
        COLOR_SELECT_FORMATO_BORDE = COLOR_SELECT_FORMATO_BORDE_CLARO
        COLOR_SELECT_FORMATO_BOTON = COLOR_SELECT_FORMATO_BOTON_CLARO
        COLOR_SELECT_FORMATO_BOTON_HOVER = COLOR_SELECT_FORMATO_BOTON_HOVER_CLARO
        COLOR_SELECT_FORMATO_DROPDOWN_FONDO = COLOR_SELECT_FORMATO_DROPDOWN_FONDO_CLARO
        COLOR_SELECT_FORMATO_DROPDOWN_TEXTO = COLOR_SELECT_FORMATO_DROPDOWN_TEXTO_CLARO
        COLOR_SELECT_FORMATO_DROPDOWN_HOVER = COLOR_SELECT_FORMATO_DROPDOWN_HOVER_CLARO

        # Textbox Formato
        COLOR_TEXBOX_FORMATO_FONDO = COLOR_TEXBOX_FORMATO_FONDO_CLARO
        COLOR_TEXBOX_FORMATO_TEXTO = COLOR_TEXBOX_FORMATO_TEXTO_CLARO
        COLOR_TEXBOX_FORMATO_PLACEHOLDER = COLOR_TEXBOX_FORMATO_PLACEHOLDER_CLARO
        COLOR_TEXBOX_FORMATO_BORDE = COLOR_TEXBOX_FORMATO_BORDE_CLARO

        # Botón Examinar
        COLOR_BOTON_EXAMINAR_FONDO = COLOR_BOTON_EXAMINAR_FONDO_CLARO
        COLOR_BOTON_EXAMINAR_HOVER = COLOR_BOTON_EXAMINAR_HOVER_CLARO
        COLOR_BOTON_EXAMINAR_TEXTO = COLOR_BOTON_EXAMINAR_TEXTO_CLARO


        # Botón "x" por renglón
        COLOR_BOTON_X_TEXTO = COLOR_BOTON_X_TEXTO_CLARO


        #barra progreso claro
        COLOR_BARRA_PROGRESO_FONDO = COLOR_BARRA_PROGRESO_FONDO_CLARO
        COLOR_BARRA_PROGRESO_RELLENO = COLOR_BARRA_PROGRESO_RELLENO_CLARO


        # Texto "URL:" igual al fondo de la ventana principal (modo claro)
        COLOR_TEXTO_URL = COLOR_TEXTO_URL_CLARO


# Carga el modo guardado (o crea el JSON la primera vez)
cargar_modo_desde_json()

# Aplica colores activos según el modo
actualizar_tema()
